from __future__ import annotations

import json
from pathlib import Path


CONFIG_PRESETS: dict[str, dict[str, object]] = {
    "cpp-cmake-gcovr": {
        "test_command": "ctest --test-dir build --output-on-failure",
        "coverage_command": "gcovr -r . --xml-pretty -o coverage.xml",
        "coverage_report": "coverage.xml",
        "source_dirs": ["src", "include"],
        "test_dirs": ["tests", "test"],
        "exclude": ["build", ".ut-cover", "third_party", "external", "vendor"],
        "unit_test_include": ["*test*", "*unittest*", "*unit*"],
        "unit_test_exclude": [],
        "dt_test_patterns": [
            "*integration*",
            "*e2e*",
            "*system*",
            "*dt*",
            "*device*",
            "*driver*",
            "*hardware*",
            "*scenario*",
            "*acceptance*",
        ],
        "preferred_test_roots": ["tests", "test"],
        "report_dir": ".ut-cover/reports",
    },
    "python-unittest": {
        "test_command": "python -m unittest discover",
        "coverage_command": "python -m coverage run -m unittest discover && python -m coverage json -o coverage.json",
        "coverage_report": "coverage.json",
        "source_dirs": ["src"],
        "test_dirs": ["tests"],
        "exclude": [".venv", "venv", "node_modules", "dist", "build"],
        "unit_test_include": ["tests/test_*.py", "tests/**/*test*.py"],
        "unit_test_exclude": [],
        "dt_test_patterns": [
            "*integration*",
            "*e2e*",
            "*system*",
            "*dt*",
            "*device*",
            "*driver*",
            "*hardware*",
            "*scenario*",
            "*acceptance*",
        ],
        "preferred_test_roots": ["tests"],
        "report_dir": ".ut-cover/reports",
    },
    "python-pytest": {
        "test_command": "python -m pytest",
        "coverage_command": "python -m pytest --cov=src --cov-report=json:coverage.json",
        "coverage_report": "coverage.json",
        "source_dirs": ["src"],
        "test_dirs": ["tests"],
        "exclude": [".venv", "venv", "node_modules", "dist", "build"],
        "unit_test_include": ["tests/test_*.py", "tests/**/*test*.py"],
        "unit_test_exclude": [],
        "dt_test_patterns": [
            "*integration*",
            "*e2e*",
            "*system*",
            "*dt*",
            "*device*",
            "*driver*",
            "*hardware*",
            "*scenario*",
            "*acceptance*",
        ],
        "preferred_test_roots": ["tests"],
        "report_dir": ".ut-cover/reports",
    },
    "node-jest": {
        "test_command": "npm test",
        "coverage_command": "npm test -- --coverage --coverageReporters=cobertura",
        "coverage_report": "coverage/cobertura-coverage.xml",
        "source_dirs": ["src"],
        "test_dirs": ["tests", "__tests__"],
        "exclude": ["node_modules", "dist", "build", "coverage"],
        "unit_test_include": ["**/*.test.*", "**/*.spec.*", "__tests__/**/*"],
        "unit_test_exclude": [],
        "dt_test_patterns": [
            "*integration*",
            "*e2e*",
            "*system*",
            "*dt*",
            "*device*",
            "*driver*",
            "*hardware*",
            "*scenario*",
            "*acceptance*",
        ],
        "preferred_test_roots": ["tests", "__tests__"],
        "report_dir": ".ut-cover/reports",
    },
}


def detect_preset(repo: str | Path) -> str:
    repo_path = Path(repo).resolve()
    if _looks_like_cpp_cmake(repo_path):
        return "cpp-cmake-gcovr"
    if _looks_like_node_jest(repo_path):
        return "node-jest"
    if _looks_like_python_pytest(repo_path):
        return "python-pytest"
    if _looks_like_python(repo_path):
        return "python-unittest"
    return "python-unittest"


def render_config(
    preset_name: str,
    test_command: str | None = None,
    coverage_command: str | None = None,
    coverage_report: str | None = None,
) -> str:
    if preset_name not in CONFIG_PRESETS:
        names = ", ".join(sorted(CONFIG_PRESETS))
        raise ValueError(f"Unknown preset: {preset_name}. Available presets: {names}")

    data = dict(CONFIG_PRESETS[preset_name])
    if test_command:
        data["test_command"] = test_command
    if coverage_command:
        data["coverage_command"] = coverage_command
    if coverage_report:
        data["coverage_report"] = coverage_report

    return "\n".join(
        [
            "# Generated by ut-cover init-config.",
            "# Edit this file if your project uses different test or coverage commands.",
            f"# preset: {preset_name}",
            "",
            f"test_command: {quote_yaml(str(data['test_command']))}",
            f"coverage_command: {quote_yaml(str(data['coverage_command']))}",
            f"coverage_report: {quote_yaml(str(data['coverage_report']))}",
            "",
            "source_dirs:",
            *[f"  - {quote_yaml(str(item))}" for item in data["source_dirs"]],
            "",
            "test_dirs:",
            *[f"  - {quote_yaml(str(item))}" for item in data["test_dirs"]],
            "",
            "exclude:",
            *[f"  - {quote_yaml(str(item))}" for item in data["exclude"]],
            "",
            "unit_test_include:",
            *[f"  - {quote_yaml(str(item))}" for item in data["unit_test_include"]],
            "",
            "unit_test_exclude:",
            *[f"  - {quote_yaml(str(item))}" for item in data["unit_test_exclude"]],
            "",
            "dt_test_patterns:",
            *[f"  - {quote_yaml(str(item))}" for item in data["dt_test_patterns"]],
            "",
            "preferred_test_roots:",
            *[f"  - {quote_yaml(str(item))}" for item in data["preferred_test_roots"]],
            "",
            f"report_dir: {quote_yaml(str(data['report_dir']))}",
            "",
        ]
    )


def quote_yaml(value: str) -> str:
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def _looks_like_cpp_cmake(repo: Path) -> bool:
    if (repo / "CMakeLists.txt").exists():
        return True
    cpp_suffixes = {".cpp", ".cc", ".cxx", ".c", ".hpp", ".hh", ".hxx", ".h"}
    for path in _iter_files(repo):
        if path.suffix.lower() in cpp_suffixes:
            return True
    return False


def _looks_like_node_jest(repo: Path) -> bool:
    if any((repo / name).exists() for name in ["jest.config.js", "jest.config.ts", "jest.config.cjs"]):
        return True
    package_json = repo / "package.json"
    if not package_json.exists():
        return False
    try:
        data = json.loads(package_json.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return False
    scripts = data.get("scripts", {}) if isinstance(data, dict) else {}
    deps = {}
    if isinstance(data, dict):
        deps.update(data.get("dependencies", {}) or {})
        deps.update(data.get("devDependencies", {}) or {})
    script_text = " ".join(str(value) for value in scripts.values()) if isinstance(scripts, dict) else ""
    return "jest" in deps or "jest" in script_text


def _looks_like_python_pytest(repo: Path) -> bool:
    if any((repo / name).exists() for name in ["pytest.ini", "tox.ini"]):
        return True
    pyproject = repo / "pyproject.toml"
    if pyproject.exists():
        text = pyproject.read_text(encoding="utf-8", errors="ignore").lower()
        return "pytest" in text
    requirements = repo / "requirements.txt"
    if requirements.exists():
        text = requirements.read_text(encoding="utf-8", errors="ignore").lower()
        return "pytest" in text
    return False


def _looks_like_python(repo: Path) -> bool:
    if any((repo / name).exists() for name in ["pyproject.toml", "setup.py", "setup.cfg"]):
        return True
    return any(path.suffix == ".py" for path in _iter_files(repo))


def _iter_files(repo: Path):
    ignored = {".git", ".venv", "venv", "node_modules", "build", "dist", ".ut-cover"}
    for path in repo.rglob("*"):
        if any(part in ignored for part in path.relative_to(repo).parts):
            continue
        if path.is_file():
            yield path
